### ISSUE TITLE
trouble running hello world - possibly down to region? af-south-1

### ISSUE THREAD

**Issue by ilanc** [nessjs/ness#191]
Hi Adam,
I've tried to deploy a static `index.html` using ness and not had any luck. Here's the repo: https://github.com/ilanc/ness-test

What I see:
```sh
$ ness deploy --dir public --profile ilan --verbose

✔ Validating AWS credentials (Account #366730223589)
```
It just ends there and returns to the shell prompt.

There's a single static file in the `public` dir:

```sh
$ ll public/
total 12
drwxrwxr-x 2 ilan ilan 4096 Aug  2 09:28 ./
drwxrwxr-x 4 ilan ilan 4096 Aug  2 09:42 ../
-rw-rw-r-- 1 ilan ilan  492 Aug  2 09:31 index.html
```

Here's my env:
```log
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
$ node --version
v16.4.2
$ aws --version
aws-cli/2.2.25 Python/3.8.8 Linux/5.4.0-80-generic exe/x86_64.ubuntu.18 prompt/off
$ nvm --version
0.38.0
```

My aws config is set as:
```txt
[profile ilan]
region = af-south-1
output = json
```

**Comment by adamelmore** [comment]
I'll give this a test and get back to you!

**Comment by ilanc** [comment]
Thanks @adamelmore. I'm not sure whether the region is to blame. I tried it with `eu-west-2` and got the same problem. I'll try on a different machine this evening (ubuntu 20).

**Comment by ilanc** [comment]
On the other machine I get a different error:

```sh
(node:12483) UnhandledPromiseRejectionWarning: ValidationError: Stack [ness-web-ness-test-master] does not exist
    at deserializeAws_queryDescribeStackEventsCommandError (/code/ness-test/node_modules/@aws-sdk/client-cloudformation/dist/cjs/protocols/Aws_query.js:1872:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /code/ness-test/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /code/ness-test/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/code/ness-test/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /code/ness-test/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async Object.getCloudFormationFailureReason (/code/ness-test/node_modules/ness/lib/providers/aws/index.js:354:38)
    at async handleError (/code/ness-test/node_modules/ness/lib/components/Deploy.js:64:24)
    at async Object.handleWebDeployed [as onComplete] (/code/ness-test/node_modules/ness/lib/components/Deploy.js:165:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
(node:12483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

✔ Validating AWS credentials (Account #366730223589)
✘ Deploying web infrastructure
```

Is there a command which I can run using `aws` cli which can test whether I have the correct permissions? I have added ` AdministratorAccess` to the account

**Comment by ilanc** [comment]
I also found a bucket that has been created `ness-toolkit-bucket-1d37lrgy691mu` in the wrong region = `us-east-1`

**Comment by ilanc** [comment]
Hi @adamelmore. Are you able to deploy my static html test repo? Is it something I've misconfigured? is there a way to reset/undo any changes which ness makes to my aws account? so that I can start from scratch.

**Comment by cdash04** [comment]
I'm having the same issue with my website here: https://github.com/cdash04/website
